list1=[1,2,5,4,3]
list1.sort()
print("SORT:",list1)
list1.reverse()
print("REVERSE:",list1)
print("INDEX OF 5:",list1.index(5))
list1.append(6)
print("APPEND:",list1)
list1.extend([1,2])
print("EXTEND:",list1)
print("COUNT OF 1:",list1.count(1))
list1.insert(3,4)
print("INSERTING 4 IN INDEX 3:",list1)
list1.pop(5)
print("REMOVING VALUE IN INDEX 5\nAFTER REMOVING INDEX 5:",list1)
list1.remove(3)
print("REMOVING VALUE 3\nAFTER REMOVING 3:",list1)
list1.clear()
print("AFTER CLEARING LIST1:",list1)
