str1=input("Enter a string")
print("capitalize:",str1.capitalize())
print("count of a",str1.count("a"))
print("center",str1.center(10))
print("isalnum",str1.isalnum())
print("isalpha",str1.isalpha())
print("isdigit",str1.isalpha())
print("upper",str1.upper())
print("lower",str1.lower())
print("length",len(str1))
