str1=input("Enter a string:")
print("1.capitalize:",str1.capitalize())
print("2.count of a:",str1.count("a"))
print("3.center:",str1.center(10))
print("4.isalnum:",str1.isalnum())
print("5.isalpha:",str1.isalpha())
print("6.isdigit:",str1.isalpha())
print("7.upper:",str1.upper())
print("8.lower:",str1.lower())
print("9.length:",len(str1))
print("10.does the string ends with a:",str1.endswith('a'))
print("11.position of 'a' in the string using find() method:",str1.find('a'))
print("12.position of 'a' in the string using index() method:",str1.index('a'))
print("13.replacing 'a' with 'e':",str1.replace('a','e'))
print("14.position of last 'a' in the string using find method:",str1.rfind('a'))
print("15.position of last 'a' in the string using find method:",str1.rfind('a'))
print("16.splitting the string where there is space:",str1.split(' '))
print("17.changing upper case to lower case and vice versa:",str1.swapcase())
print("18.lower case of string using casefold() method:",str1.casefold())
print("19.encoded version of the string:",str1.encode())
print("20.right justify of the string:",str1.rjust(100))


