str1=input("Enter a string:")
print("1.capitalize:",str1.capitalize())
print("2.count of a:",str1.count("a"))
print("3.center:",str1.center(10))
print("4.isalnum:",str1.isalnum())
print("5.isalpha:",str1.isalpha())
print("6.isdigit:",str1.isalpha())
print("7.upper:",str1.upper())
print("8.lower:",str1.lower())
print("9.length:",len(str1))
print("10.does the string ends with a:",str1.endswith('a'))
print("11.position of 'a' in the string using find() method:",str1.find('a'))
print("12.position of 'a' in the string using index() method:",str1.index('a'))
print("13.replacing 'a' with 'e':",str1.replace('a','e'))
print("14.position of last 'a' in the string using find method:",str1.rfind('a'))
print("15.position of last 'a' in the string using find method:",str1.rindex('a'))
print("16.splitting the string where there is space:",str1.split(' '))
print("17.changing upper case to lower case and vice versa:",str1.swapcase())
print("18.lower case of string using casefold() method:",str1.casefold())
print("19.encoded version of the string:",str1.encode())
print("20.right justify of the string:",str1.rjust(100))
print("21.tab size:",str1.expandtabs(4))
print("22.I'm from {}".format("India"))
print("23.isdicimal:",str1.isdecimal())
print("24.isidentifier:",str1.isidentifier())
print("25.isnumeric:",str1.isnumeric())
print("26.isprintable:",str1.isprintable())
print("27.isspace:",str1.isspace())
print("28.istitle:",str1.istitle())
print("29.islower:",str1.islower())
print("30.isupper:",str1.isupper())
print("31.left justify of the string:",str1.ljust(100))
print("32.lstrip of .............hello:","...........hello".lstrip('.'))
print("33.maketrans of 'a' and 'e':",str1.maketrans('a','e'))
print("34.partition:",str1.partition(' '))
print("35.r-partition:",str1.rpartition(' '))
print("36.r-split:",str1.rsplit(' '))
print("37.r-strip:",str1.rstrip(" "))
print("38.splitline:",str1.splitlines())
print("39.strip:",str1.strip(' '))
print("40.title:",str1.title())
print("41.concadenation:","hello" + "world")
print("42.repetition:",str1*3)


